# Generated by Django 4.2.6 on 2023-10-18 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jongmaihub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jongmaihub.appointment'),
        ),
    ]
