# Generated by Django 4.2.4 on 2023-10-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jongmaihub', '0002_alter_rating_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_picture',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='cover_picture',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_picture',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=models.TextField(default=None),
        ),
    ]
